### ISSUE TITLE
Need help: How to completely remove Hugo?

### ISSUE THREAD

**Issue by eallion** [stuartleeks/vscode-hugo-runner#1]

**Comment by stuartleeks** [comment]
Do you mean you have installed Hugo via the extension and want to remove it?

If so, it would also be useful to understand why.

**Comment by eallion** [comment]
Perhaps it will occupy port 1313 for a long time, run the previously installed Hugo with the error: `listen tcp 0.0.0.0:1313: bind: An attempt was made to access a socket in a way forbidden by its access permissions`
